id = "c3"
name = "C3"
version = "0.1.0"
schema_version = 1
authors = ["Aiden Olsen <olsenaiden33@gmail.com>","Tumuer Zunong <muerzunong.tu@gmail.com>"]
description = "C3 language support for Zed."
repository = "https://github.com/un4gt/c3-zed-next"
languages = ["languages/c3"]
snippets = ["./snippets/c3.json"]

[language_servers.c3]
name = "C3 LSP"
languages = ["C3"]
language_ids = { C3 = "c3" }

[grammars.c3]
repository = "https://github.com/c3lang/tree-sitter-c3"
rev = "1c6a95234c62130763ed1c479f958b74fdbfdb2a"
